### ISSUE TITLE
Ask about plans to fully release the code

### ISSUE THREAD

**Issue by eanson023** [minjoong507/MPGN#1]
Hi authors,

Thank you very much for your contribution, very good work. Recently I read some articles about VCMR. The current shortcoming of this field is that it is open source and there is too little code for learning. I would like to ask the author if he plans to release the code for your reference. Thank you very much, waiting for your reply...

Best Regards,

Sheng Yan
2024-01-02

**Comment by minjoong507** [comment]
Hi @eanson023 

Thank you for your interest in our work.

I am planning to share the code for this project in the future, but I'm not quite sure when that will be. 

It has been some time since I last worked on this project.

I will notify you as soon as I upload the code for this project. 

Thank you for your patience and understanding.

Best regards.

**Comment by eanson023** [comment]
Thank you for replying to my message.  Looking forward to it....

**Comment by eanson023** [comment]
Hi @minjoong507 

I would like to ask you how you obtained the original video to generate pseudo queries when you participated in this project. I first submitted the application at [TQVA](https://tvqa.cs.unc.edu/download_tvqa.html#tvqa-download-4), but there has been no official reply, so I have not been able to get the raw video to conduct the next experiment. QAQ...

Best Regards,

Sheng Yan
2024-01-09

**Comment by minjoong507** [comment]
Hi @eanson023,

 As far as I know, we cannot download raw videos in [TVQA datasets](https://tvqa.cs.unc.edu/download_tvqa.html#tvqa-download-4). Hence, we utilized video frames to generate pseudo queries, which can be downloaded upon form completion.

Currently, I'm in the process of cleaning up our project's code for reproducibility. I might be able to upload the codes in the coming days. Once I finish this task, I'll notify you immediately.

Thank you.

**Comment by eanson023** [comment]
Hi @minjoong507 , the author of TVQA has approved my application to download the raw video. Thank you for your tip.

**Comment by minjoong507** [comment]
Hi @eanson023,

We just released our codes for this project. 

If you face any issues while running our codes, please leave a comment here.

Thank you.

**Comment by eanson023** [comment]
thank you. I would like to ask you about using pseudo query data generated by a third-party model to train the model. Will the reviewers question this way of raising points (I’m new to this, so I don’t really understand it, lol...)
