### ISSUE TITLE
What is the role of tvr_video2dur_idx.json file?

### ISSUE THREAD

**Issue by fuseniory** [minjoong507/MPGN#2]
Hello! I would like to ask, what is the role of tvr_video2dur_idx.json file? I didn't see relevant information in the paper, please explain to me, thank you!

**Comment by minjoong507** [comment]
Hi, @fuseniory 

Thanks for your interest in our work!

I remember that `tvr_video2dur_idx.json` file is borrowed from the TVR repository. 

It only contains meta information for the videos in datasets, so we do not need this file for the model's training.

You may check [here](https://github.com/jayleicn/TVRetrieval/blob/d99a9ea7e724249047d6357f2a607c7ae256f8c6/baselines/crossmodal_moment_localization/start_end_dataset.py#L213) how the TVR uses this file.

Please let me know if there are any further questions.

Thank you.
